apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-cntr
  labels:
    env: sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      env: sandbox
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: auth-cntr
        image: auth-img
        ports:
        - containerPort: 1090